### PR TITLE
Preemptor lost in preemption action

### LINKED ISSUE #950: preemptor missing when preempting in same job
This case should preempt two pods in same job with low priority
```sh
create(){
    kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    useKubeBatch: "true"
  name: preeptee
  namespace: default
spec:
  backoffLimit: 2
  completions: 2
  parallelism: 2
  ttlSecondsAfterFinished: 600  
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: group1
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ['/bin/sh']
        args: ['-c', 'sleep 160']        
        resources:
          requests:
            cpu: 1000m
          #limits:
          #  nvidia.com/gpu: 3             
      restartPolicy: Never
      terminationGracePeriodSeconds: 5
      schedulerName: kube-batch
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: group1
  namespace: default
spec:
  minMember: 1
  queue: default
EOF

    sleep 10
    kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: preeptor
  namespace: default
spec:
  backoffLimit: 2
  completions: 2
  parallelism: 2
  ttlSecondsAfterFinished: 600  
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: group1
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ['/bin/sh']
        args: ['-c', 'sleep 120']        
        resources:
          requests:
            cpu: 1000m
      restartPolicy: Never
      terminationGracePeriodSeconds: 5
      schedulerName: kube-batch
      priorityClassName: high-priority
EOF
}
```

**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug report
> Uncomment only one, leave it on its own line:
>
> kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by lowang-bh**
**What this PR does / why we need it**:
Fix issue #950 
In preemption action, it wil first try to preempt from other jobs and will pop preemptor from preemptorTasks queue which is used to record the preeptor tasks. This cause preemptorTasks miss one preemptor task at least when There is no other jobs can be preempted and try to preempt other tasks in the same job

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #950
when preempt task between same job's tasks, it should compare task's priority in this job;

**Special notes for your reviewer**:

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by k82cn** [comment]
@lowang-bh would you help to share more backgroup of this PR?

**Comment by lowang-bh** [comment]
> @lowang-bh would you help to share more backgroup of this PR?

consider the preemption between same job's tasks, 
It wil first try to preempt from other jobs and will pop preemptor from preemptorTasks which is used to record the preeptor tasks. This cause preemptorTasks miss one preemptor task at least when There is no other jobs can be preempted and try to preempt other tasks in the same job.
for example:
```sh
create(){
    kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    useKubeBatch: "true"
  name: preeptee
  namespace: default
spec:
  backoffLimit: 2
  completions: 2
  parallelism: 2
  ttlSecondsAfterFinished: 600  
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: group1
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ['/bin/sh']
        args: ['-c', 'sleep 160']        
        resources:
          requests:
            cpu: 1000m
          #limits:
          #  nvidia.com/gpu: 3             
      restartPolicy: Never
      terminationGracePeriodSeconds: 5
      schedulerName: kube-batch
---
apiVersion: scheduling.incubator.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: group1
  namespace: default
spec:
  minMember: 1
  queue: default
EOF

    sleep 10
    kubectl apply -f - <<EOF
apiVersion: batch/v1
kind: Job
metadata:
  name: preeptor
  namespace: default
spec:
  backoffLimit: 2
  completions: 2
  parallelism: 2
  ttlSecondsAfterFinished: 600  
  template:
    metadata:
      annotations:
        scheduling.k8s.io/group-name: group1
    spec:
      containers:
      - image: busybox
        imagePullPolicy: IfNotPresent
        name: busybox
        command: ['/bin/sh']
        args: ['-c', 'sleep 120']        
        resources:
          requests:
            cpu: 1000m
      restartPolicy: Never
      terminationGracePeriodSeconds: 5
      schedulerName: kube-batch
      priorityClassName: high-priority
EOF
}
```

**Comment by mrbobbytables** [comment]
Repo is to be archived, for more information please see: https://github.com/kubernetes/org/issues/4200

/close

**Pull request closed without merging**
